#! /bin/sh

if test -d "$1"/.svn ; then
	DATE=`LC_ALL=C svn info "$1" | sed -n 's/^Last Changed Date: \(.*\)/\1/p'`
	REVISION=`LC_ALL=C svn info "$1" | sed -n 's/^Last Changed Rev: \(.*\)/\1/p'`
	VERSION_DATE=`echo $DATE | cut -f 1 -d ' ' | tr -d -`
	VERSION_TIME=`echo $DATE | cut -f 2 -d ' ' | awk -F: '{printf "%0.4d", $1$2}'`
	echo "#define XBH_REVISION \"$REVISION\""
	echo "#define XBH_VERSION_DATE \"$VERSION_DATE\""
	echo "#define XBH_VERSION_TIME \"$VERSION_TIME\""
else
	exit 1
fi
