# Generated automatically from Makefile.in by configure.
SHELL= /bin/sh 

SUBDIRS = default

all: 
	for dir in ${SUBDIRS} ; do ( cd $$dir ; ${MAKE} all ) ; done

clean:
	for dir in ${SUBDIRS} ; do ( cd $$dir ; ${MAKE} clean ) ; done
	 